### ISSUE TITLE
Please support library only tokens

### ISSUE THREAD

**Issue by sdsys-ch** [vquie/n8n-nodes-seafile#1]
Hi @vquie ,
Thanks for this. Nice start! For the current functionality, can you please differentiate between global api tokens and library api tokens?

The api endpoint for getting an upload link is slightly different, the returned upload link has the same properties/ endpoint as the regular one. 

See [this link](https://download.seafile.com/published/web-api/v2.1/library-api-tokens.md) for details.

I can share a current implementation with the http request node, if you like. But it's pretty straightforward. I just wonder where in n8n to select that it's a library only token? Maybe in the credentials, if that's possible? That would allow for a differentiation in get_upload_url... The alternative would be to test if request has successfully returned a url for uploading and if not retry with the library endpoint. Not sure that's better...

Thanks for looking into this!

**Comment by vquie** [comment]
I didn't even know you could create an upload link with the library API token. :-D

Will add this when I find some spare time.

**Comment by vquie** [comment]
@sdsys-ch 
Please try the new 1.1.0 release. Please also keep in mind, that not all actions allow the library key, i.e. delete. I couldn't find any documentation on how to delete with the library token.

**Comment by sdsys-ch** [comment]
Hey @vquie 

Thank you for implementing this. Been using it and works as expected. Kudos!

Also: Just FYI since it's beta release, but looks like Seafile Pro 11.0.4 Beta supports `Library Tokens` with regular rw/del etc.: [Seafile 11.0.4 Beta Changelog](https://manual.seafile.com/changelog/changelog-for-seafile-professional-server/#1104-beta-and-seadoc-05-2024-02-01) states `Add move dir/file, copy dir/file, delete dir/file, rename dir/file APIs for library token based API` among other changes. Haven't tested as I only have production instances with v10 atm.

I'm closing this and thank you again for this node!
